name: Run API Tests and Publish Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run API Tests and generate HTML report
        run: |
          mkdir -p report
          newman run "collection/FakeStore API Tests.postman_collection.json" \
            -e "environment/FakeStore Env.postman_environment.json" \
            -r html --reporter-html-export report/index.html

      - name: Deploy HTML report to gh-pages branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          cp report/index.html gh-pages/index.html
          cd gh-pages
          git add index.html
          git commit -m "📄 Update HTML test report"
          git push
