name: Run API Tests (CLI only)

on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: |
          newman run "collection/FakeStore API Tests.postman_collection.json" \
            -e "environment/FakeStore Env.postman_environment.json"
