name: Run API Tests

on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run API Tests and Generate Report
        run: |
          mkdir -p report
          newman run "collection/FakeStore API Tests.postman_collection.json" \
            -e "environment/FakeStore Env.postman_environment.json" \
            -r html --reporter-html-export report/index.html

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: report/index.html
